apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd-infra
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: ">0.0.0"  # Utiliser toujours la dernière version disponible
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd  # Namespace où Argo CD sera déployé
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/ThomasInfras/k8s-automated-kind'
    targetRevision: HEAD
    path: argocd.kind.nixos.local/applis

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         