apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-ops-view
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.christianhuth.de'
    chart: kube-ops-view
    targetRevision: ">0.0.0"
    helm:
      values: |
        ingress:
          enabled: true
          className: "nginx"
          labels:
            gethomepage.dev/enabled: "true"
          annotations:
            gethomepage.dev/enabled: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            gethomepage.dev/name: "kube-ops-view"
            gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: "kube-ops-view.kind.nixos.local"
              paths:
                - path: /
                  pathType: ImplementationSpecific

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-ops-view  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      