apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://jameswynn.github.io/helm-charts'
    chart: homepage
    targetRevision: ">0.0.0" 
    helm:
      valueFiles:
        - values.yaml 
      values: |
        enableRbac: true

        extraClusterRoles:
          # - apiGroups:
          #   - some-group
          #   resources:
          #   - some-resource
          #   verbs:
          #   - get

        serviceAccount:
          # Specify a different service account name. When blank it will default to the release
          # name if *create* is enabled, otherwise it will refer to the default service account.
          name: ""
          # Create service account. Needed when RBAC is enabled.
          create: true      
        config:
          widgets:
            - resources:
                # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
                backend: kubernetes
                expanded: true
                cpu: true
                memory: true
            - search:
                provider: duckduckgo
                target: _blank
            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "cluster"
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true   
          kubernetes:
            mode: cluster                           
        ingress:
          main:
            enabled: true
            labels:
              # This label will enable discover of this deployment in Homepage
              gethomepage.dev/enabled: "true"
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              gethomepage.dev/name: "HomepageCUSTOM"
              gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
            ingressClassName: "nginx"
            hosts:
              - host: &host "home.kind.nixos.local"
                paths:
                  - path: /
                    pathType: Prefix

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage  # Changez le namespace si nécessaire
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   