apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
  project: default
  source:
    repoURL: 'https://github.com/ThomasHelmCharts/argocd-applications'
    path: ./
    targetRevision: "HEAD" 
    helm:
      valueFiles:
        - values.yaml
      values: |
        apps_values:
          domain: ".kind.nixos.local"        
        apps:
          kube-ops-view:
            spec:
              sources:
                - repoURL: 'https://charts.christianhuth.de'
                  chart: kube-ops-view
                  targetRevision: '">0.0.0"'
                  helm:
                    values: |
                      host: kube-ops-view{{ $.Values.apps_values.domain }}
                      ingress:
                        enabled: true
                        className: "nginx"
                        labels:
                          gethomepage.dev/enabled: "true"
                        annotations:
                          gethomepage.dev/enabled: "true"
                          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                          gethomepage.dev/name: "kube-ops-view"
                          gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
                          # kubernetes.io/ingress.class: nginx
                          # kubernetes.io/tls-acme: "true"
                        hosts:
                          - host: kube-ops-view{{ $.Values.apps_values.domain }}
                            paths:
                              - path: /
                                pathType: ImplementationSpecific
          homepage:
            spec:
              sources:
                - repoURL: 'https://jameswynn.github.io/helm-charts'
                  chart: homepage
                  targetRevision: '">0.0.0"' 
                  helm:
                    valueFiles:
                      - values.yaml 
                    values: |
                      host: &host home{{ $.Values.apps_values.domain }}
                      enableRbac: true
                      serviceAccount:
                        create: true
                      config:
                        settings:
                          background: 
                            image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
                            blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
                            saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
                            brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
                            opacity: 50 # 0-100
                          quicklaunch:
                            searchDescriptions: true
                            hideInternetSearch: true
                            showSearchSuggestions: true
                            hideVisitURL: true
                            provider: google                       
                          headerStyle: boxedWidgets
                        services: {}
                        widgets:                          
                          - resources:
                              # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
                              backend: kubernetes
                              expanded: true
                              cpu: true
                              memory: true
                          - search:
                              target: _blank
                              quicklaunch:
                                searchDescriptions: true
                                hideInternetSearch: true
                                showSearchSuggestions: true
                                hideVisitURL: true
                              provider: google                                 
                          - kubernetes:
                              cluster:
                                show: true
                                cpu: true
                                memory: true
                                showLabel: true
                                label: "cluster"
                              nodes:
                                show: true
                                cpu: true
                                memory: true
                                showLabel: true   
                        kubernetes:
                          mode: cluster                           
                      ingress:
                        main:
                          enabled: true
                          labels:
                            gethomepage.dev/enabled: "true"
                          annotations:
                            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                            gethomepage.dev/name: "HomepageCUSTOM"
                            gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
                          ingressClassName: "nginx"
                          hosts:
                            - host: *host
                              paths:
                                - path: /
                                  pathType: Prefix
